spring:
  application:
    name: zuul
    
server:
  port: 3001
rabbitmq:
   host: 192.168.159.131
   port: 5672
   username: admin
   password: admin  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#一下是zuul的默认配置(若是每有配备一下信息,他会从eureka拉取信息)
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
    #开启重试
  retryable: true
#ribbon重试的相关配置  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
#可以不设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    